name = "TaleOfTwoPandemics"
uuid = "c6f588ca-d5e0-4481-a91b-5747b4202a7a"
authors = ["Anastasia Golovin <asgolovin@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
